version: '3.4'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    restart: always
    volumes:
      - .:/usr/app
      - ./usr/app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres:14.4-alpine
    build:
      dockerfile: ./postgres-db/Dockerfile
      context: ./postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
#     volumes:
#       - postgres-db:/var/lib/postgresql/data
# volumes:
#   docker-nest-postgres:
