version: '3.9'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    restart: always
    volumes:
      - .:/usr/app
      - ./usr/app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}

    depends_on:
      - postgres
    networks:
      - container-net
        # name: homelib-net
        # driver: bridge
  postgres:
    build: ./postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - container-net
networks:
  container-net:
    name: container-net
    driver: bridge
volumes:
  pgdata:
