version: '3.9'

services:
  api:
    image: matvi/music-library:server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - container-net
    command: node dist/main.js

  postgres:
    image: matvi/music-library:db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - .:/var/lib/postgresql/data
    networks:
      - container-net
networks:
  container-net:
    name: container-net
    driver: bridge
